[0m00:33:06.094221 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BD04B46E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BD04B93DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BD04B729D0>]}


============================== 00:33:06.098779 | 12909acf-302a-461e-b174-9634bb27a16a ==============================
[0m00:33:06.098779 [info ] [MainThread]: Running with dbt=1.9.3
[0m00:33:06.099797 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\bosst\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:33:06.100796 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\DE_study\Project\etl_metadata_framework\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:33:06.101796 [debug] [MainThread]: Command `dbt run` failed at 00:33:06.101796 after 0.10 seconds
[0m00:33:06.102834 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BD04BB55D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BD04B50410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BD04B729D0>]}
[0m00:33:06.102834 [debug] [MainThread]: Flushing usage events
[0m00:33:07.292395 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:34:00.700044 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B891185410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B8911D3590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B8911B3410>]}


============================== 13:34:00.704142 | 3e7e6f6b-eace-4c84-9f2f-9950548aa76b ==============================
[0m13:34:00.704142 [info ] [MainThread]: Running with dbt=1.9.3
[0m13:34:00.705338 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\bosst\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:34:00.706628 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\DE_study\Project\etl_metadata_framework\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:34:00.707646 [debug] [MainThread]: Command `dbt run` failed at 13:34:00.706628 after 0.09 seconds
[0m13:34:00.707646 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B8911F7B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B891190350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B8911869D0>]}
[0m13:34:00.708646 [debug] [MainThread]: Flushing usage events
